AWSTemplateFormatVersion: '2010-09-09'
Description: Staging S3 buckets for Cloudlabs custom templates 

# S3 Buckets for Cloudlabs templates

Resources:
  WizlabsCLTemplatesBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Purpose
          Value: Cloudlabs_Template_Storage

  WizlabsCLTemplatesLogsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      Tags:
        - Key: Purpose
          Value: Event Logs Storage for Cloudlabs template bucket

  


